all: fix comment typos
Fix two comment typos reported by Codespell:
	Error: ./src/syscalls.c:292: pseduo ==> pseudo
	Error: ./src/gen_pfc.c:247: pseduo ==> pseudo

Signed-off-by: Tom Hromatka <tom.hromatka@oracle.com>
(cherry picked from commit d5f77038335d523da509e0c246da8be794c511b7)